import type { DiscoveredLead, LeadDiscoveryProvider, LeadDiscoveryQuery } from "./types";

export class MockLeadDiscoveryProvider implements LeadDiscoveryProvider {
  name = "mock";
  async discover(query: LeadDiscoveryQuery): Promise<DiscoveredLead[]> {
    const industry = query.industry?.trim() || "Service business";
    const location = query.location?.trim() || "Finland";
    const companySize = query.companySize?.trim() || "1–10 employees";
    const keywords = query.keywords?.filter(Boolean) ?? [];
    const samples: DiscoveredLead[] = [
      { companyName: "Northstar Services", domain: "northstar-example.fi", website: "https://northstar-example.fi", industry, location, companySize, description: "Example prospect generated by the LeadFlow mock discovery provider.", whyRelevant: keywords.length ? `Matches the requested focus: ${keywords.join(", ")}.` : `Matches the selected ${industry} and ${location} criteria.` },
      { companyName: "Aurora Works", domain: "aurora-works-example.fi", website: "https://aurora-works-example.fi", industry, location, companySize, description: "Example prospect for testing the discovery workflow safely.", whyRelevant: `Matches the selected ${industry} and ${location} criteria.` },
      { companyName: "Summit Local", domain: "summit-local-example.fi", website: "https://summit-local-example.fi", industry, location, companySize, description: "Example prospect for validating import, deduplication and review.", whyRelevant: `Matches the selected ${industry} and ${location} criteria.` },
    ];
    return samples.slice(0, Math.max(1, Math.min(query.limit, samples.length)));
  }
}
