"use client";
import { useActionState, useEffect, useRef, useState } from "react";
import { addDiscoveredLeadsAction, discoverLeadsAction } from "@/app/(app)/leads/discover/actions";
const discoveryInitial = { results: [], error: null }; const addInitial = { message: null, error: null };
const inputClass = "w-full rounded-xl border border-white/[0.09] bg-white/[0.035] px-3.5 py-3 text-sm text-slate-100 outline-none placeholder:text-slate-500 transition focus:border-violet-400/50 focus:ring-4 focus:ring-violet-500/[0.08]";
export function DiscoveryForm({ locale }: { locale: "fi" | "en" }) {
  const fi=locale==="fi"; const [discovery,discover,finding]=useActionState(discoverLeadsAction,discoveryInitial); const [addState,addSelected,adding]=useActionState(addDiscoveredLeadsAction,addInitial);
  const [provider,setProvider]=useState<"prh-ytj"|"google-places">("prh-ytj"); const [providerOpen,setProviderOpen]=useState(false); const providerRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{ const close=(event:MouseEvent)=>{ if(providerRef.current&&!providerRef.current.contains(event.target as Node)) setProviderOpen(false); }; document.addEventListener("mousedown",close); return()=>document.removeEventListener("mousedown",close); },[]);
  return <div className="space-y-6"><form action={discover} className="surface rounded-3xl p-6 sm:p-7"><div className="grid gap-5 sm:grid-cols-2">
    <div className="text-sm font-medium text-slate-200 sm:col-span-2" ref={providerRef}><div>{fi?"Hakutapa":"Search source"}</div><input type="hidden" name="provider" value={provider}/><div className="relative mt-2"><button type="button" onClick={()=>setProviderOpen((open)=>!open)} aria-expanded={providerOpen} className="flex w-full items-center justify-between rounded-xl border border-white/[0.09] bg-white/[0.035] px-4 py-3 text-left outline-none transition hover:border-violet-400/30 focus:border-violet-400/50 focus:ring-4 focus:ring-violet-500/[0.08]"><span><span className="block text-sm font-medium text-slate-100">{provider==="prh-ytj"?(fi?"PRH/YTJ – maksuton yrityshaku":"PRH/YTJ – free company search"):"Google Places"}</span><span className="mt-0.5 block text-xs font-normal text-slate-500">{provider==="prh-ytj"?(fi?"Suomen yritysrekisteri · ensisijainen hakutapa":"Finnish company register · primary source"):(fi?"Paikalliset yritykset · käytä tarvittaessa":"Local businesses · use when needed")}</span></span><span className={`ml-4 text-slate-500 transition ${providerOpen?"rotate-180":""}`}>⌄</span></button>{providerOpen&&<div className="absolute z-30 mt-2 w-full overflow-hidden rounded-xl border border-white/[0.1] bg-[#111119] p-1.5 shadow-2xl shadow-black/40"><button type="button" onClick={()=>{setProvider("prh-ytj");setProviderOpen(false)}} className={`w-full rounded-lg px-3 py-2.5 text-left transition ${provider==="prh-ytj"?"bg-violet-500/15 text-violet-200":"text-slate-200 hover:bg-white/[0.05]"}`}><span className="block text-sm font-medium">{fi?"PRH/YTJ – maksuton yrityshaku":"PRH/YTJ – free company search"}</span><span className="mt-0.5 block text-xs font-normal text-slate-500">{fi?"Suomen yritysrekisteri, ei Google-hakukuluja":"Finnish company register, no Google search cost"}</span></button><button type="button" onClick={()=>{setProvider("google-places");setProviderOpen(false)}} className={`mt-1 w-full rounded-lg px-3 py-2.5 text-left transition ${provider==="google-places"?"bg-violet-500/15 text-violet-200":"text-slate-200 hover:bg-white/[0.05]"}`}><span className="block text-sm font-medium">Google Places</span><span className="mt-0.5 block text-xs font-normal text-slate-500">{fi?"Paikallisiin yrityksiin, joita PRH-haku ei löydä":"For local businesses PRH search does not find"}</span></button></div>}</div></div>
    <label className="text-sm font-medium text-slate-200">{fi?"Toimiala":"Industry"}<input name="industry" placeholder={fi?"esim. rakennusala":"e.g. construction"} className={`mt-2 ${inputClass}`}/></label>
    <label className="text-sm font-medium text-slate-200">{fi?"Sijainti":"Location"}<input name="location" placeholder="esim. Jyväskylä" className={`mt-2 ${inputClass}`}/></label>
    <label className="text-sm font-medium text-slate-200">{fi?"Yrityksen koko":"Company size"}<input name="companySize" placeholder={fi?"esim. 1–20 työntekijää":"e.g. 1–20 employees"} className={`mt-2 ${inputClass}`}/></label>
    <label className="text-sm font-medium text-slate-200">{fi?"Tarpeet / avainsanat":"Needs / keywords"}<input name="keywords" placeholder={fi?"SEO, verkkosivut, uudistus":"SEO, website, renovation"} className={`mt-2 ${inputClass}`}/></label>
  </div>{discovery.error&&<div className="mt-5 rounded-xl border border-red-400/20 bg-red-400/[0.06] px-4 py-3 text-sm text-red-200">{discovery.error}</div>}<div className="mt-6 flex justify-end border-t border-white/[0.07] pt-5"><button disabled={finding} className="rounded-xl bg-violet-500 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{finding?(fi?"Etsitään...":"Finding leads..."):(fi?"Etsi liidejä":"Find leads")}</button></div></form>
  {discovery.results.length?<form action={addSelected} className="surface overflow-hidden rounded-3xl"><div className="flex items-center justify-between border-b border-white/[0.07] px-6 py-5"><div><h2 className="font-semibold text-slate-100">{fi?"Hakutulokset":"Discovery results"}</h2><p className="mt-1 text-xs text-slate-400">{fi?"Tarkista yritykset ennen niiden lisäämistä liideihin.":"Review the companies before adding them to your pipeline."}</p></div><span className="rounded-full border border-white/[0.08] bg-white/[0.04] px-3 py-1 text-xs text-slate-300">{discovery.results.length} {fi?"löytyi":"found"}</span></div><div className="divide-y divide-white/[0.07]">{discovery.results.map((lead,index)=><label key={lead.domain??`${lead.companyName}-${index}`} className="grid cursor-pointer gap-3 px-6 py-5 sm:grid-cols-[24px_1.2fr_1fr]"><input type="checkbox" name="selectedLead" value={JSON.stringify(lead)} defaultChecked className="mt-1 h-4 w-4 accent-violet-500"/><div><div className="font-medium text-slate-100">{lead.companyName}</div><div className="mt-1 text-xs text-slate-400">{lead.domain??(fi?"Verkkotunnusta ei löytynyt":"No domain found")}</div></div><div><div className="text-sm text-slate-300">{lead.industry??(fi?"Toimiala ei tiedossa":"Industry unknown")} · {lead.location??(fi?"Sijainti ei tiedossa":"Location unknown")}</div><div className="mt-1 text-xs leading-5 text-slate-400">{lead.whyRelevant??(fi?"Tarkista ennen lisäämistä.":"Review before adding.")}</div></div></label>)}</div>{(addState.error||addState.message)&&<div className="px-6 pt-5"><div className={addState.error?"rounded-xl border border-red-400/20 bg-red-400/[0.06] px-4 py-3 text-sm text-red-200":"rounded-xl border border-emerald-400/20 bg-emerald-400/[0.06] px-4 py-3 text-sm text-emerald-200"}>{addState.error??addState.message}</div></div>}<div className="flex justify-end border-t border-white/[0.07] px-6 py-5"><button disabled={adding} className="rounded-xl bg-violet-500 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{adding?(fi?"Lisätään...":"Adding..."):(fi?"Lisää valitut liideihin":"Add selected to leads")}</button></div></form>:null}</div>;
}
